stages:
  - test
  - build


nix-check:
  stage: test
  needs: []
  tags:
    - nix
  script:
    - nix --extra-experimental-features 'nix-command flakes' flake check

nix:
  stage: build
  needs: [ ]
  tags:
    - nix
  script:
    - nix --extra-experimental-features 'nix-command flakes' build -L
